name: docker pust latest

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
#        uses: docker/build-push-action@v2
        run: |
          npm install
          npm test
          docker build -t joshuamshana/bfastfunction:latest .
          docker push joshuamshana/bfastfunction:latest
        with:
          push: true
          tags: joshuamshana/bfastfunction:latest


#          docker push joshuamshana/bfastfunction:latest
#          docker logout
#          echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
#          npm run push:latest


#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
#        node-version: [ 16.x ]
#
#    steps:
#      - uses: actions/checkout@v1
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ matrix.node-version }}
#      - name: publish to docker as latest
#        run: |
#          npm install
#          npm test
#          docker logout
#          echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
#          npm run push:latest
#        env:
#          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#          CI: true
